[tools]
actionlint = "latest"
pre-commit = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
opentofu = "latest"
task = "latest"
terragrunt = "latest"
yamllint = "latest"
zizmor = "latest"
k9s = "latest"
kubectl = "latest"
helm = "latest"
